local bit = require("gdpr.iab.tcfv2.bit")
local base64 = require("gdpr.iab.tcfv2.base64")
local BitStream = require("gdpr.iab.tcfv2.bitstream")

describe("Plumbing", function()
  describe("Bit bridge", function()
    it("performs band correctly", function()
      assert.are.equal(0, bit.band(0xF0, 0x0F))
    end)

    it("performs bor correctly", function()
      assert.are.equal(0xFF, bit.bor(0xF0, 0x0F))
    end)

    it("performs lshift correctly", function()
      assert.are.equal(16, bit.lshift(1, 4))
    end)

    it("performs rshift correctly", function()
      assert.are.equal(1, bit.rshift(16, 4))
    end)
  end)

  describe("Base64url", function()
    it("decodes simple strings", function()
      local decoded = base64.decode_url("AB")
      assert.are.equal(string.char(0), decoded)
    end)

    it("decodes TCF header snippet", function()
      local decoded = base64.decode_url("COw")
      assert.are.equal(0x08, string.byte(decoded, 1))
      assert.are.equal(0xEC, string.byte(decoded, 2))
    end)
  end)

  describe("BitStream", function()
    it("reads integers correctly", function()
      local decoded = base64.decode_url("COw")
      local bs = BitStream.new(decoded)
      assert.are.equal(2, bs:read_int(6))
      assert.are.equal(14, bs:read_int(6))
      assert.are.equal(12, bs:read_int(4))
    end)

    it("reads booleans correctly", function()
      local bs = BitStream.new(string.char(0x80)) -- 10000000
      assert.is_true(bs:read_bool())
      assert.is_false(bs:read_bool())
    end)

    it("handles peek and seek", function()
      local bs = BitStream.new(string.char(0xFF))
      assert.are.equal(15, bs:peek_int(4))
      assert.are.equal(0, bs:pos())
      assert.are.equal(255, bs:read_int(8))
      bs:seek(4)
      assert.are.equal(15, bs:read_int(4))
    end)
  end)
end)
